{
  "uid" : "326aa052ea2942bd",
  "name" : "test_login",
  "fullName" : "377_testcase.test_login.TestLogin#test_login",
  "historyId" : "8d28a733387dda61e2fa433d6fa8efee",
  "time" : {
    "start" : 1699539512629,
    "stop" : 1699539512629,
    "duration" : 0
  },
  "description" : "用户正常登录",
  "descriptionHtml" : "<p>用户正常登录</p>\n",
  "status" : "broken",
  "statusMessage" : "urllib3.exceptions.LocationParseError: Failed to parse: http://127.0.0.1:{self.device_info['server_port']}/wd/hub/session",
  "statusTrace" : "cmdopt = \"{'platform_version': '10', 'server_port': 4723, 'system_port': 8200, 'device': 'D5F0218710007612'}\"\n\n    @pytest.fixture(scope='session')\n    def common_driver(cmdopt):\n        global driver\n        base_driver = BaseDriver(eval(cmdopt))\n>       driver = base_driver.base_driver()\n\ntestcase\\conftest.py:32: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ncommon\\base_driver.py:61: in base_driver\n    driver = webdriver.Remote(\"http://127.0.0.1:{self.device_info['server_port']}/wd/hub\", desired_caps)\nC:\\python3.8\\lib\\site-packages\\appium\\webdriver\\webdriver.py:147: in __init__\n    super(WebDriver, self).__init__(\nC:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:157: in __init__\n    self.start_session(capabilities, browser_profile)\nC:\\python3.8\\lib\\site-packages\\appium\\webdriver\\webdriver.py:227: in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\nC:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:319: in execute\n    response = self.command_executor.execute(driver_command, params)\nC:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py:374: in execute\n    return self._request(command_info[0], url, body=data)\nC:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py:397: in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\nC:\\python3.8\\lib\\site-packages\\urllib3\\request.py:79: in request\n    return self.request_encode_body(\nC:\\python3.8\\lib\\site-packages\\urllib3\\request.py:171: in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\nC:\\python3.8\\lib\\site-packages\\urllib3\\poolmanager.py:324: in urlopen\n    u = parse_url(url)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nurl = \"http://127.0.0.1:{self.device_info['server_port']}/wd/hub/session\"\n\n    def parse_url(url):\n        \"\"\"\n        Given a url, return a parsed :class:`.Url` namedtuple. Best-effort is\n        performed to parse incomplete urls. Fields not provided will be None.\n        This parser is RFC 3986 compliant.\n    \n        The parser logic and helper functions are based heavily on\n        work done in the ``rfc3986`` module.\n    \n        :param str url: URL to parse into a :class:`.Url` namedtuple.\n    \n        Partly backwards-compatible with :mod:`urlparse`.\n    \n        Example::\n    \n            >>> parse_url('http://google.com/mail/')\n            Url(scheme='http', host='google.com', port=None, path='/mail/', ...)\n            >>> parse_url('google.com:80')\n            Url(scheme=None, host='google.com', port=80, path=None, ...)\n            >>> parse_url('/foo?bar')\n            Url(scheme=None, host=None, port=None, path='/foo', query='bar', ...)\n        \"\"\"\n        if not url:\n            # Empty\n            return Url()\n    \n        source_url = url\n        if not SCHEME_RE.search(url):\n            url = \"//\" + url\n    \n        try:\n            scheme, authority, path, query, fragment = URI_RE.match(url).groups()\n            normalize_uri = scheme is None or scheme.lower() in NORMALIZABLE_SCHEMES\n    \n            if scheme:\n                scheme = scheme.lower()\n    \n            if authority:\n                auth, host, port = SUBAUTHORITY_RE.match(authority).groups()\n                if auth and normalize_uri:\n                    auth = _encode_invalid_chars(auth, USERINFO_CHARS)\n                if port == \"\":\n                    port = None\n            else:\n                auth, host, port = None, None, None\n    \n            if port is not None:\n                port = int(port)\n                if not (0 <= port <= 65535):\n                    raise LocationParseError(url)\n    \n            host = _normalize_host(host, scheme)\n    \n            if normalize_uri and path:\n                path = _remove_path_dot_segments(path)\n                path = _encode_invalid_chars(path, PATH_CHARS)\n            if normalize_uri and query:\n                query = _encode_invalid_chars(query, QUERY_CHARS)\n            if normalize_uri and fragment:\n                fragment = _encode_invalid_chars(fragment, FRAGMENT_CHARS)\n    \n        except (ValueError, AttributeError):\n>           return six.raise_from(LocationParseError(source_url), None)\nE           urllib3.exceptions.LocationParseError: Failed to parse: http://127.0.0.1:{self.device_info['server_port']}/wd/hub/session\n\nC:\\python3.8\\lib\\site-packages\\urllib3\\util\\url.py:392: LocationParseError",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 1,
  "retriesStatusChange" : false,
  "beforeStages" : [ {
    "name" : "_verify_url",
    "time" : {
      "start" : 1699539511611,
      "stop" : 1699539511611,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0,
    "stepsCount" : 0,
    "hasContent" : false
  }, {
    "name" : "pytestconfig",
    "time" : {
      "start" : 1699539511611,
      "stop" : 1699539511611,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0,
    "stepsCount" : 0,
    "hasContent" : false
  }, {
    "name" : "base_url",
    "time" : {
      "start" : 1699539511611,
      "stop" : 1699539511611,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "feature",
    "value" : "登录"
  }, {
    "name" : "story",
    "value" : "正常登录"
  }, {
    "name" : "severity",
    "value" : "blocker"
  }, {
    "name" : "parentSuite",
    "value" : "377_testcase"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "DESKTOP-CHVCFJK"
  }, {
    "name" : "thread",
    "value" : "22564-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "377_testcase.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "blocker",
    "retries" : [ {
      "uid" : "f66e86dc0518aad5",
      "status" : "broken",
      "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command ''C:\\\\Program Files (x86)\\\\Android\\\\android-sdk\\\\platform-tools\\\\adb.exe' -P 5037 -s D5F0218710007612 shell pm install /data/local/tmp/appium_cache/4a3611f83607e4a76c33e4d83ef4a4b6e0b619a6.apk' exited with code 1'; Command output: Failure [INSTALL_FAILED_ABORTED: User rejected permissions]",
      "time" : {
        "start" : 1699529797871,
        "stop" : 1699529797871,
        "duration" : 0
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "326aa052ea2942bd.json",
  "parameterValues" : [ ]
}