{"name": "登录T9Y0221C09002076", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details\n    at UIA2Proxy.command (C:\\Users\\YM520\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\jsonwp-proxy\\proxy.js:274:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AndroidUiautomator2Driver.commands.getScreenshot (C:\\Users\\YM520\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-driver\\lib\\commands\\screenshot.js:14:10)", "trace": "self = <pageViwe.loginPage.LoginPage object at 0x000001F0180DA550>\ndoc = '我的_用户名', loc = ('id', 'com.xkw.client:id/mine_username')\n\n    def find_element(self, *loc, doc=\"\") -> WebElement:\n        \"\"\"\n        查找单个元素方法\n        :type doc: 定位元素界面位置：例如 首页\n        :type loc: 元素定位\n        \"\"\"\n        try:\n            logging.info(\"{} 页面开始查找元素{}\".format(doc, loc))\n>           WebDriverWait(self.driver, 20, 0.5).until(EC.visibility_of_element_located(loc))\n\npageViwe\\basePage.py:32: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nC:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:86: in until\n    value = method(self._driver)\nC:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:152: in _predicate\n    return _element_if_visible(driver.find_element(*locator))\nC:\\python3.8\\lib\\site-packages\\appium\\webdriver\\webdriver.py:409: in find_element\n    return self.execute(RemoteCommand.FIND_ELEMENT, {'using': by, 'value': value})['value']\nC:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:345: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <appium.webdriver.errorhandler.MobileErrorHandler object at 0x000001F0180DA430>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"An unknown server-side error occurred while pro...\\\\\\node_modules\\\\\\\\appium\\\\\\\\node_modules\\\\\\\\appium-base-driver\\\\\\\\lib\\\\\\\\basedriver\\\\\\\\commands\\\\\\\\find.js:53:10)\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"\n        https://www.w3.org/TR/webdriver/#errors\n        \"\"\"\n        payload = response.get('value', '')\n        try:\n            payload_dict = json.loads(payload)\n        except (json.JSONDecodeError, TypeError):\n            return\n        if not isinstance(payload_dict, dict):\n            return\n        value = payload_dict.get('value')\n        if not isinstance(value, dict):\n            return\n        error = value.get('error')\n        if not error:\n            return\n    \n        message = value.get('message', error)\n        stacktrace = value.get('stacktrace', '')\n        # In theory, we should also be checking HTTP status codes.\n        # Java client, for example, prints a warning if the actual `error`\n        # value does not match to the response's HTTP status code.\n        exception_class: Type[sel_exceptions.WebDriverException] = ERROR_TO_EXC_MAPPING.get(\n            error, sel_exceptions.WebDriverException\n        )\n        if exception_class is sel_exceptions.WebDriverException and message:\n            if message == 'No such context found.':\n                exception_class = appium_exceptions.NoSuchContextException\n            elif message == 'That command could not be executed in the current context.':\n                exception_class = appium_exceptions.InvalidSwitchToTargetException\n    \n        if exception_class is sel_exceptions.UnexpectedAlertPresentException:\n            raise sel_exceptions.UnexpectedAlertPresentException(\n                msg=message,\n                stacktrace=format_stacktrace(stacktrace),\n                alert_text=value.get('data'),\n            )\n>       raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))\nE       selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details\nE       Stacktrace:\nE       UnknownError: An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details\nE           at UIA2Proxy.command (C:\\Users\\YM520\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\jsonwp-proxy\\proxy.js:274:13)\nE           at processTicksAndRejections (node:internal/process/task_queues:95:5)\nE           at AndroidUiautomator2Driver.helpers.doFindElementOrEls (C:\\Users\\YM520\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-driver\\lib\\commands\\find.js:32:12)\nE           at doFind (C:\\Users\\YM520\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-android-driver\\lib\\commands\\find.js:36:17)\nE           at wrappedCondFn (C:\\Users\\YM520\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\basedriver\\commands\\timeout.js:151:12)\nE           at spin (C:\\Users\\YM520\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\asyncbox\\lib\\asyncbox.js:138:20)\nE           at waitForCondition (C:\\Users\\YM520\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\asyncbox\\lib\\asyncbox.js:155:10)\nE           at AndroidUiautomator2Driver.implicitWaitForCondition (C:\\Users\\YM520\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\basedriver\\commands\\timeout.js:153:10)\nE           at AndroidUiautomator2Driver.findElOrEls (C:\\Users\\YM520\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-android-driver\\lib\\commands\\find.js:60:5)\nE           at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\\Users\\YM520\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\basedriver\\commands\\find.js:33:12)\nE           at AndroidUiautomator2Driver.findElement (C:\\Users\\YM520\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\basedriver\\commands\\find.js:53:10)\n\nC:\\python3.8\\lib\\site-packages\\appium\\webdriver\\errorhandler.py:122: WebDriverException\n\nDuring handling of the above exception, another exception occurred:\n\nself = <testcase.test_login.TestLogin object at 0x000001F01813CA00>\ncommon_driver = <pageViwe.loginPage.LoginPage object at 0x000001F0180DA550>\ndevice = {'device': 'T9Y0221C09002076', 'platform_version': '12', 'server_port': 4723, 'system_port': 8200}\n\n    @allure.story(\"正常登录\")\n    @allure.description(\"用户正常登录\")  # 用例的描述\n    @allure.severity(allure.severity_level.BLOCKER)\n    def test_login(self, common_driver, device):\n        allure.dynamic.title(\"登录\" + device[\"device\"])\n        common_driver.login('XXX', 'XXX')\n>       common_driver.result_assert(common_driver.get_username(), \"xkw_03314932\", '用户正常登录')\n\ntestcase\\test_login.py:27: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npageViwe\\loginPage.py:57: in get_username\n    return self.get_text(*self.login_btn, doc=\"我的_用户名\")\npageViwe\\basePage.py:114: in get_text\n    ele = self.find_element(*loc, doc=doc)\npageViwe\\basePage.py:38: in find_element\n    screen_name = self.get_screenshot(doc)\npageViwe\\basePage.py:208: in get_screenshot\n    self.driver.get_screenshot_as_file(pic_name)\nC:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:802: in get_screenshot_as_file\n    png = self.get_screenshot_as_png()\nC:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:836: in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\nC:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:847: in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\nC:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:345: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <appium.webdriver.errorhandler.MobileErrorHandler object at 0x000001F0180DA430>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"An unknown server-side error occurred while pro...\\\\\\node_modules\\\\\\\\appium\\\\\\\\node_modules\\\\\\\\appium-uiautomator2-driver\\\\\\\\lib\\\\\\\\commands\\\\\\\\screenshot.js:14:10)\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"\n        https://www.w3.org/TR/webdriver/#errors\n        \"\"\"\n        payload = response.get('value', '')\n        try:\n            payload_dict = json.loads(payload)\n        except (json.JSONDecodeError, TypeError):\n            return\n        if not isinstance(payload_dict, dict):\n            return\n        value = payload_dict.get('value')\n        if not isinstance(value, dict):\n            return\n        error = value.get('error')\n        if not error:\n            return\n    \n        message = value.get('message', error)\n        stacktrace = value.get('stacktrace', '')\n        # In theory, we should also be checking HTTP status codes.\n        # Java client, for example, prints a warning if the actual `error`\n        # value does not match to the response's HTTP status code.\n        exception_class: Type[sel_exceptions.WebDriverException] = ERROR_TO_EXC_MAPPING.get(\n            error, sel_exceptions.WebDriverException\n        )\n        if exception_class is sel_exceptions.WebDriverException and message:\n            if message == 'No such context found.':\n                exception_class = appium_exceptions.NoSuchContextException\n            elif message == 'That command could not be executed in the current context.':\n                exception_class = appium_exceptions.InvalidSwitchToTargetException\n    \n        if exception_class is sel_exceptions.UnexpectedAlertPresentException:\n            raise sel_exceptions.UnexpectedAlertPresentException(\n                msg=message,\n                stacktrace=format_stacktrace(stacktrace),\n                alert_text=value.get('data'),\n            )\n>       raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))\nE       selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details\nE       Stacktrace:\nE       UnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details\nE           at UIA2Proxy.command (C:\\Users\\YM520\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\jsonwp-proxy\\proxy.js:274:13)\nE           at processTicksAndRejections (node:internal/process/task_queues:95:5)\nE           at AndroidUiautomator2Driver.commands.getScreenshot (C:\\Users\\YM520\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-driver\\lib\\commands\\screenshot.js:14:10)\n\nC:\\python3.8\\lib\\site-packages\\appium\\webdriver\\errorhandler.py:122: WebDriverException"}, "description": "用户正常登录", "steps": [{"name": "我的页面，点击切换到我的页面", "status": "passed", "start": 1698074069960, "stop": 1698074074889}, {"name": "我的页面，点击登录", "status": "passed", "start": 1698074074889, "stop": 1698074075694}, {"name": "我的_登录页面_切换到用户密码登录", "status": "passed", "attachments": [{"name": "我的_登录_密码登录", "source": "10b009fd-e538-4057-bf0a-7dd5c1eebb96-attachment.png", "type": "image/png"}, {"name": "我的_登录_密码登录", "source": "ef9082b6-1640-45b3-8823-d08d8b6438bc-attachment.png", "type": "image/png"}], "start": 1698074075694, "stop": 1698074097184}, {"name": "我的_账号密码登录页面，输入账号:XXX", "status": "passed", "attachments": [{"name": "登录_用户名输入框", "source": "9741d48f-1618-45bb-acf9-eacef39c2aff-attachment.png", "type": "image/png"}, {"name": "登录_用户名输入框", "source": "8972673c-6fda-4d9b-91b6-de9900da08bf-attachment.png", "type": "image/png"}], "start": 1698074097184, "stop": 1698074118652}, {"name": "我的_账号密码登录页面，输入密码:XXX", "status": "passed", "attachments": [{"name": "登录_密码输入框", "source": "e9c70d30-3203-4f5c-8e90-7dcff9bc67f4-attachment.png", "type": "image/png"}, {"name": "登录_密码输入框", "source": "7b9c8a6e-0fd8-44c6-90e6-c7ad4b8a5314-attachment.png", "type": "image/png"}], "start": 1698074118652, "stop": 1698074140308}, {"name": "我的_账号密码登录页面_点击提交登录", "status": "passed", "attachments": [{"name": "我的_登录_提交登录", "source": "e23c28ee-76ae-4c6a-852e-5b6c0b970d8e-attachment.png", "type": "image/png"}, {"name": "我的_登录_提交登录", "source": "e515c281-3d2a-4a6f-b603-9c79985005ef-attachment.png", "type": "image/png"}], "start": 1698074140308, "stop": 1698074162989}, {"name": "获取用户名", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details\n    at UIA2Proxy.command (C:\\Users\\YM520\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\jsonwp-proxy\\proxy.js:274:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AndroidUiautomator2Driver.commands.getScreenshot (C:\\Users\\YM520\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-driver\\lib\\commands\\screenshot.js:14:10)\n", "trace": "  File \"C:\\study\\pythonT\\pyAppium-master\\pageViwe\\loginPage.py\", line 57, in get_username\n    return self.get_text(*self.login_btn, doc=\"我的_用户名\")\n  File \"C:\\study\\pythonT\\pyAppium-master\\pageViwe\\basePage.py\", line 114, in get_text\n    ele = self.find_element(*loc, doc=doc)\n  File \"C:\\study\\pythonT\\pyAppium-master\\pageViwe\\basePage.py\", line 38, in find_element\n    screen_name = self.get_screenshot(doc)\n  File \"C:\\study\\pythonT\\pyAppium-master\\pageViwe\\basePage.py\", line 208, in get_screenshot\n    self.driver.get_screenshot_as_file(pic_name)\n  File \"C:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 802, in get_screenshot_as_file\n    png = self.get_screenshot_as_png()\n  File \"C:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 836, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"C:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 847, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"C:\\python3.8\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 345, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\python3.8\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 122, in check_response\n    raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))\n"}, "start": 1698074162989, "stop": 1698074165419}], "attachments": [{"name": "log", "source": "8803523a-e61a-457f-9438-0a1f947b8140-attachment.txt", "type": "text/plain"}], "start": 1698074069960, "stop": 1698074165429, "uuid": "a4b02a1d-42ee-4e0e-a6ad-d1b3f667aeb6", "historyId": "ff2fe0402b19b5fe9aa73c6e14418ce9", "testCaseId": "ff2fe0402b19b5fe9aa73c6e14418ce9", "fullName": "239_testcase.test_login.TestLogin#test_login", "labels": [{"name": "severity", "value": "blocker"}, {"name": "feature", "value": "登录"}, {"name": "story", "value": "正常登录"}, {"name": "parentSuite", "value": "239_testcase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-CHVCFJK"}, {"name": "thread", "value": "12688-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "239_testcase.test_login"}]}